//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edPractice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID_order { get; set; }
        public int Count { get; set; }
        public int ID_client { get; set; }
        public System.DateTime Order_date { get; set; }
        public string datess
        {
            get
            {
                Console.WriteLine(Order_date.ToShortDateString());
                return Order_date.ToShortDateString();
            }
        }
        public bool Status { get; set; }
        public int ID_trip { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
