//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edPractice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int ID_trip { get; set; }
        public int ID_client { get; set; }
        public int ID_country { get; set; }
        public System.DateTime Trip_start { get; set; }
        public System.DateTime Trip_end { get; set; }
        public int Price { get; set; }
        public int Discount { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Country Country { get; set; }
    }
}
